### ISSUE TITLE
For HBridgeMotor pwmFrequency can be specified - but 1600 is always used anyway

### ISSUE THREAD

**Issue by MarkAlanJones** [WildernessLabs/Meadow.Foundation#109]
`public HBridgeMotor(IPwmPort a1Pin, IPwmPort a2Pin, IDigitalOutputPort enablePin, float pwmFrequency = 1600)
        {
            _pwmFrequency = pwmFrequency;

            _motorLeftPwm = a1Pin;
            _motorLeftPwm.Frequency = 1600;
            _motorLeftPwm.Start();

            _motorRighPwm = a2Pin;
            _motorRighPwm.Frequency = 1600;
            _motorRighPwm.Start();

            _enablePort = enablePin;
        }`

Maybe 1600 is the only good value - then it shouldn't be specified ?

**Comment by jorgedevs** [comment]
I'll check this out, you're most likely right, thanks for reporting this @MarkAlanJones ! 👍

**Comment by MarkAlanJones** [comment]
Upon further testing - i found with my motors that the 1600 made a noticeable audible tone
the tone is higher until around 10000 - when it is mostly non audible - younger hackers may still hear this
I ended up using 12000.  

Higher frequency should give the motor a more consistent voltage ?

**Comment by bryancostanich** [comment]
Might consider using a capacitor at the output to smooth the voltage: https://hackaday.com/2011/06/16/beginner-concepts-using-a-low-pass-filter-to-smooth-pwm-output/

**Comment by adrianstevens** [comment]
This is fixed in Meadow.Core - will ship with B5.3 - thx @MarkAlanJones!

**Comment by adrianstevens** [comment]
B5.3 has shipped - closing issue
