### ISSUE TITLE
wildernesslabs.meadow.assemblies 0.4.0 dependencies & deployment behaviour.

### ISSUE THREAD

**Issue by HowardvanRooijen** [WildernessLabs/Meadow.Foundation#116]
Not sure if this is the right repo for issues with the [WildernessLabs.Meadow.Assemblies](https://www.nuget.org/packages/WildernessLabs.Meadow.Assemblies) package.

I noticed that the size of the package has ballooned from 3.06mb in v[0.32](https://www.nuget.org/packages/WildernessLabs.Meadow.Assemblies/0.3.2) to 16.73mb in v[0.4](https://www.nuget.org/packages/WildernessLabs.Meadow.Assemblies/0.4.0)

When I upgrade my dependency on Meadow.Foundation to v 0.19 the dependencies now reflect all those assemblies. When I try and debug the application via Visual Studio it now tries to deploy all those assemblies

![2020-10-26_07-46-04](https://user-images.githubusercontent.com/128664/97168248-0742c080-1780-11eb-95c2-af49cc63971c.png)

And hangs on System.Xml - I suspect because the Meadow board has run out of space, but the deployment just hangs.

Not sure if these are intended side effects?

I'm also seeing this behaviour when I try and deploy / run / debug any apps:

https://community.wildernesslabs.co/t/unable-to-load-dll-nuttx/1348

**Comment by jorgedevs** [comment]
Hi @HowardvanRooijen ,

The reason the WildernessLabs.Meadow.Assemblies package got bigger is that it now includes a fairly complete set of BCLs. This is to increase the compatibility with more NuGets packages. However, with Cecil implemented, it checks which libraries are being used and we only push over the libraries being used by the app, so the memory on the board is not compromised with things the app deployed is not using. 

With the latest version of the VS extension (0.12.3), it only writes the dlls the app is using.
