### ISSUE TITLE
Calling Led.StartBlink when the Led is on causes a flicker

### ISSUE THREAD

**Issue by csuski** [WildernessLabs/Meadow.Foundation#12]
If you call Led.StartBlink() on a Led that is currently set to on it turns it off briefly before turning it back on at the beginning of the blink cycle.

I found this unexpected and the only way to figure out why it was flickering was to look at the implementation of StartBlink().  

I think turning off the LED before the start of the blink sequence should be removed. It forces anyone who wants to go from the ON state to the Blink state to have a flicker and there is no way around it without writing your own implementation (and I can't imagine this is the desired before for anyone).

**Comment by gasia89** [comment]
I have a fix for this, but I am having permissions issues with the repo at the moment.

**Comment by gasia89** [comment]
Pull request [22](https://github.com/WildernessLabs/Meadow.Foundation/pull/22) fixes this.

**Comment by bryancostanich** [comment]
See above mentioned pull request.

**Comment by jorgedevs** [comment]
PR reviewed and merged. Thanks!
