### ISSUE TITLE
Interrupts from MCP23008 don't work as expected

### ISSUE THREAD

**Issue by pseabury** [WildernessLabs/Meadow.Foundation#121]
Wiring up a single MCP input port with a switch to pull it low, should generate an interrupt on the configured Meadow interrupt pin via MCP23008.INT, but it does not in this configuration.  

I would expect that every time MCP.GP7 gets pulled low by pressing the button, an interrupt on Meadow should fire.  

As a secondary issue, even if an interrupt was generated, with this code the MCP.INT pin is not reset to GND when the button is released, but only when the pin is manually read again in the application loop - confirmed via Voltmeter.  In other words, if I press the button, I get 3V3 on the meter immediately from MCP.INT, but when I release the button I don't get GND until the app loop calls

`_mcp000.ReadPort(_mcp000_GP7.Pin);`

Repro code is here - https://gist.github.com/pseabury/86fc28a3be74644fdf951c2c3b90402a

[EDIT] - Updated Fritzing to show the pullup resistors that are actually part of the prototype circuit.

![MCP23008_Meadow_Interrupts](https://user-images.githubusercontent.com/1918526/102725947-4e60b400-42e0-11eb-9333-6ad739b82319.png)

**Comment by adrianstevens** [comment]
This is fixed and will ship with the the next release
