### ISSUE TITLE
`Display.ClearScreen(color)` doesn't seem to do anything

### ISSUE THREAD

**Issue by bryancostanich** [WildernessLabs/Meadow.Foundation#125]
I would expect these to clear and fill the screen with whatever colors:
```
// these don't seem to do anything
//display.ClearScreen(8);
//display.ClearScreen(156);
//display.ClearScreen(1000);
//display.ClearScreen(40980);
```

does not. 

---

Also, if do intend to support this API, we may want to take a color struct.

**Comment by adrianstevens** [comment]
Strongly agree - I think this method is specific to the TftSpi display - I'll fix it now since it's public but I'll also add a proper version to uGraphics

**Comment by adrianstevens** [comment]
Fixed in WIP - will publish for B4.3
