### ISSUE TITLE
MCP23x08 Driver bugs

### ISSUE THREAD

**Issue by ctacke** [WildernessLabs/Meadow.Foundation#127]
the MCP driver has a couple issues:
1. Meadow Interrupts are generated at creation.  Just creating the MCP instance and an instance of an InputPort on it generates two unwanted interrupts on the Meadow interrupt pin.
2. Interrupts stop unless you manually read the State on the input after the interrupt has happened.

**Comment by upswing1** [comment]
Any updates on this?

**Comment by adrianstevens** [comment]
#2 is fixed and will ship with the next release
