### ISSUE TITLE
µGraphics Library : Text Align Center doesn't take scale factor into account

### ISSUE THREAD

**Issue by bryancostanich** [WildernessLabs/Meadow.Foundation#129]
Given the following code (where `dW ==` _display width_), i would expect to see the text centered in the screen, but is not:

```csharp
canvas.DrawText(
    (int)dW/2, 10, $"{climate.CurrentConditions.Temperature.Value:###°}",
    WLabsColors.Blue, GraphicsLibrary.ScaleFactor.X3,
    GraphicsLibrary.TextAlignment.Center);
```

In looking at the graphics source, i believe [this line](https://github.com/WildernessLabs/Meadow.Foundation/blob/main/Source/Meadow.Foundation.Libraries_and_Frameworks/Graphics/MicroGraphics/Driver/Graphics.MicroGraphics/GraphicsLibrary.cs#L898), should be maybe:

```csharp
x = x - text.Length * ((CurrentFont.Width * scaleFactor) >> 1);
```

**Comment by adrianstevens** [comment]
Fixed in the above commit - will pub w B4.4
