### ISSUE TITLE
PiezoSpeaker fails on Frequencies less than 1

### ISSUE THREAD

**Issue by csuski** [WildernessLabs/Meadow.Foundation#16]
The PiezoSpeaker.PlayTone method throws an exception if the frequency is set less than or equal to 0, but if you pass in a frequency under 1 the board stops responding.

Running the code below works, but if you uncomment the .9f code section the board will stop and never make it to last tone.  It isn't clear what happens, it keeps playing the .9f frequency tone, but never executes any more code.

```
public class MeadowApp : App<F7Micro, MeadowApp>
    {
        Meadow.Foundation.Audio.PiezoSpeaker piezo;
        public MeadowApp()
        {
            ConfigurePorts();
            TestPiezo();
        }

        public void ConfigurePorts()
        {
            Console.WriteLine("Creating Inputs...");
            piezo = new Meadow.Foundation.Audio.PiezoSpeaker(Device.CreatePwmPort(Device.Pins.D10));
        }

        public void TestPiezo()
        {
            Console.WriteLine("Plate Tone 100");
            piezo.PlayTone(100);
            Thread.Sleep(500);

            Console.WriteLine("Plate Tone 1");
            piezo.PlayTone(1f);
            Thread.Sleep(500);

            //Console.WriteLine("Plate Tone .9");
            //piezo.PlayTone(.9f);
            //Thread.Sleep(500);

            Console.WriteLine("Plate Tone 100");
            piezo.PlayTone(100);
            Thread.Sleep(500);

        }
}
```

**Comment by bryancostanich** [comment]
@adrianstevens i believe that the MCU PWM can only go so slow. I ran into this with the PID PWM control in the dehydrator, and had to switch to SoftPwm.

We should figure out what that limit is, document it, and in the case of piezo, probably do a check. I'm not sure what a tone of less than 1 would be anyway.
