### ISSUE TITLE
Yx5300: `data2` is sent in place of `data1`

### ISSUE THREAD

**Issue by craigktreasure** [WildernessLabs/Meadow.Foundation#169]
Many commands are not working for the Yx5300 driver as a result of an error in the code causing `data2` to be sent in the position of `data1`. See [here](https://github.com/WildernessLabs/Meadow.Foundation/blob/main/Source/Meadow.Foundation.Peripherals/Audio.Mp3.Yx5300/Driver/Audio.Mp3.Yx5300/Yx5300.cs#L214).

```csharp
            // Command Structure 0x7E 0xFF 0x06 CMD FBACK DAT1 DAT2 0xEF
            sendBuffer[0] = 0x7E;    // Start byte
            sendBuffer[1] = 0xFF;    // Version
            sendBuffer[2] = 0x06;    // Command length not including Start and End byte.
            sendBuffer[3] = (byte)command; // Command
            sendBuffer[4] = 0x01;    // Feedback 0x00 NO, 0x01 YES
            sendBuffer[5] = data2;    // DATA1 datah
            sendBuffer[6] = data2;    // DATA2 datal
            sendBuffer[7] = 0xEF;    // End byte
```

`data2` is sent twice. `data1` should be sent for the high (`datah`) portion.

**Comment by adrianstevens** [comment]
Thanks @craigktreasure  - I'll get this fixed before the next release

**Comment by adrianstevens** [comment]
Fixed for B5.0
