### ISSUE TITLE
I2cCharacterDisplay BackLight

### ISSUE THREAD

**Issue by DmytroKoval** [WildernessLabs/Meadow.Foundation#171]
// Turn the (optional) backlight off/on
        public void BacklightOn()
        {
            backlightValue = LCD_NOBACKLIGHT;
            ExpanderWrite(0);
        }
        public void BacklightOff()
        {
            backlightValue = LCD_BACKLIGHT;
            ExpanderWrite(0);
        }

`LCD_BACKLIGHT` and `LCD_NOBACKLIGHT` are seem to be misplaced.

**Comment by adrianstevens** [comment]
Thanks @DmytroKoval  - we'll get this fixed in the next release!

**Comment by adrianstevens** [comment]
Fixed for B5.1
