### ISSUE TITLE
ICs.IOExpanders.Is31fl3731_Sample question

### ISSUE THREAD

**Issue by Tridy** [WildernessLabs/Meadow.Foundation#186]
Hi.

Is there a way to document which pins need to be connected to F7 Micro in order for it to work and if there are any extra components that are required. How did you guys test it when this sample was created? More details on how I connect it is in [this](https://community.wildernesslabs.co/t/how-to-connect-and-work-with-led-shim-is31fl3731/1583) post.

Thanks!

**Comment by adrianstevens** [comment]
Hey @Tridy I used it in the Adafruit CharliePlex 15x7 FeatherWing https://www.adafruit.com/product/3163 

It should just require 3.3V, ground, I2C data (pin 7) and I2c clock (pin 8).

If it's not working you may need pull up or pull down resistors on pins 7 & 8 (either work for I2C).

**Comment by Tridy** [comment]
I am not sure about 3.3V

the description of LED Shim says:

> Needs 5v power

https://pinout.xyz/pinout/led_shim

**Comment by adrianstevens** [comment]
Ah interesting ..... Meadow is 5V tolerant so it should be fine if you power it off of 5V

**Comment by Tridy** [comment]
Well, I got tired of trying and gave up. Maybe one day someone could create videos of actual devices wired and working, and not just look like it should work on paper. My curiosity is worn out at this point.

**Comment by adrianstevens** [comment]
Just an update - I've used this driver with another peripheral - the Mikro 16x9 Click board and it's working correctly.

That board only needs I2C clock, data, 3.3V and ground.

**Comment by adrianstevens** [comment]
closing issue
