### ISSUE TITLE
Support System.Device.Gpio

### ISSUE THREAD

**Issue by ethos-tim** [WildernessLabs/Meadow.Foundation#19]
Can Meadow support System.Device.Gpio?

https://github.com/dotnet/iot/issues/835

**Comment by bryancostanich** [comment]
We have no plans to support that API. The approach we've taken with meadow is far different. Let us know if there are any drivers that there are drivers for in Windows IoT and we'll prioritize porting them!

**Comment by frogcrush** [comment]
Hey, would you mind expanding a bit more on how meadow's approach is different? I'm just curious as I feel like it would be beneficial for the community if we reduced the fragmentation in the space. For example, nanoFramework appears to be moving to support dotnet/iot. Based on that linked issue, they also seemed to think it wouldn't be a bad idea to align the ecosystem.
