### ISSUE TITLE
Starting Maple.Server renderers the device unable to make HttpRequests

### ISSUE THREAD

**Issue by PureWeen** [WildernessLabs/Meadow.Foundation#192]
1. Go into the Secrets file and set your SSID/PWD
2. deploy to meadow
3. notice how the request to google never completes
4. if you comment out the `server.Start()` portion of the code then the request is able to complete

I'm using the latest .53b release

[HellowMeadow.zip](https://github.com/WildernessLabs/Meadow.Foundation/files/7192514/HellowMeadow.zip)

**Comment by adrianstevens** [comment]
Thx @PureWeen I'll test this week - it might be fixed in B6.0
