### ISSUE TITLE
Touch controller driver request

### ISSUE THREAD

**Issue by upswing1** [WildernessLabs/Meadow.Foundation#193]
It would be useful to use the following tft display  https://www.adafruit.com/product/2050 ..  it uses an HX8357-D00/D01 for which a driver already exists.  A touch screen driver should be added to the library so that the community at large can benefit from this component or similar touch screen tft displays.

**Comment by adrianstevens** [comment]
The challenge with this particular driver is the pins change modes between analog in and digital out ... I'm not sure if we can do this on Meadow today:

https://github.com/adafruit/Adafruit_TouchScreen/blob/master/TouchScreen.cpp

**Comment by adrianstevens** [comment]
@ctacke for visibility re switching port direction
