### ISSUE TITLE
Sensor.Atmspheric.BME280 - never turns changes  mode from Sleep to either Forced or Normal

### ISSUE THREAD

**Issue by brucecrombie** [WildernessLabs/Meadow.Foundation#195]
BME280 always returns the same valves for temperature, humidity, and pressure because the mode register is never changed from Sleep (0b00)  to either Forced (0b01) or Normal (0b11).

On startup the BME280 device would be in Sleep mode. During constructor of the Bme280 object the constructor calls the Init Method that sets the Bme280 configuration.Mode state variable to Sleep (0b00). The Init method then calls the UpdateConfiguration method to write the stored configuration states to registers 0xf4 and 0xf5.  First it sets register 0xf4 to 0x00 to put the BME280 device to sleep so that writes to BME280 registers will not be ignored. 
`bme280Comms.WriteRegister(Bme280Comms.Register.Measurement, 0x00);`
The UpdateConfiguration method then goes on to update the 0xf2, 0xf4, and 0xf5 registers on the BME280 device with the stored configuration data
```
var data = (byte)((((byte)configuration.Standby << 5) & 0xe0) | (((byte)configuration.Filter << 2) & 0x1c));
 bme280Comms.WriteRegister(Bme280Comms.Register.Configuration, data);
data = (byte)((byte)configuration.HumidityOverSampling & 0x07);
bme280Comms.WriteRegister(Bme280Comms.Register.Humidity, data);
data = (byte)((((byte)configuration.TemperatureOverSampling << 5) & 0xe0) |
                           (((byte)configuration.PressureOversampling << 2) & 0x1c) |
                           ((byte)configuration.Mode & 0x03));
bme280Comms.WriteRegister(Bme280Comms.Register.Measurement,data)
```
After initialization of the Bme280 object the state of the configuration.Mode variable and the state on the Bme280 device are both set to "Sleep"

To read data from the BME280 device ReadSensor method is invoked. by the Read method of the SensorBase class. Bme280.ReadSensor method overrides the abstract SensorBase.ReadSensor method that takes no parameters and returns a structure of atmospheric conditions.
The first thing this ReadSensor method does is update the configuration on the BME280 device but because the line that sets the  Mode to Forced or Normal instead or the current Sleep has been commented out (line 172) so the BME280 never runs to update its data.
If this line is uncommented then it is not certain what data you would get back. Once the BME280 device is set to Forced fresh data will not be available for reading until after the BME280 device has has enough time to refresh the data. See datasheet sections 9.1, 9.2, and 9.3. It is almost certain because there is no delay between the meadow writing the configuration data and then reading the temperature, pressure, and humidity data back that the data is from the previous ReadSensor invocation. If the data is read only on demand with the Read method the data could possibly be many minutes or hours old.

It is not clear to me why updating the configuration is required with every invocation of a ReadSensor method except to Force the BME280 to run for a cycle and refresh it's data. In normal mode it probably only needs to be run when a write to the BME280 registers is required. Why do we need to set the OverSampling values every time? Maybe read back the oversample registers and compare with the class properties and only write the registers if the values are different. That would allow the option of running the BME280 in  Normal mode.

Any time that the UpdateConfiguration method is run, there should be a time delay to allow the BME280 to refresh its data. That would mean Forced mode would be slower to respond than Normal mode.

Possibly the Modes (Forced and Normal) could be surfaced as a parameter when the BME280 object is newed up and allow the user to decide what mode is best for there project.

I'm not sure if this device shares common code with similar devices so I'm reluctant to do a pull request the would break the planned architecture of atmospheric measurement devices. Also this device driver looks to be a work in progress so I don't know if work is currently underway on these issues. Is this something you want me to try and craft a pull request for?

**Comment by adrianstevens** [comment]
@brucecrombie sorry for the delay, @NevynUK has verified and we'll get a fix out ASAP
