### ISSUE TITLE
Missing Meadow.Core Project.

### ISSUE THREAD

**Issue by JamestsaiTW** [WildernessLabs/Meadow.Foundation#2]
I had download the latest Code commit solution, but Visual Studio can't load Meadow.Core project.
![image](https://user-images.githubusercontent.com/9651229/54262029-31923b00-45a8-11e9-9d65-643fcd6f331e.png)

**Comment by bryancostanich** [comment]
This should be fixed now. We've pushed Meadow.Core to nuget and reference it here instead.
