### ISSUE TITLE
Menu.Enable() crashes when FontScale = 2

### ISSUE THREAD

**Issue by HuskyRiver** [WildernessLabs/Meadow.Foundation#271]
If Micrographics.DisplayConfig.FontScale is set to 2 before enabling a menu, there is an Unhandled Exception: System.IndexOutOfRangeException.

**Comment by adrianstevens** [comment]
Thanks! I'll investigate

**Comment by adrianstevens** [comment]
Thanks again @HuskyRiver  - there was also a logic error that would reset the font scale if a new font was set 

fixed - will go out with the next release
