### ISSUE TITLE
NeoPixel Support

### ISSUE THREAD

**Issue by atrueresistance** [WildernessLabs/Meadow.Foundation#28]
I wired up some [breadboard NeoPixels](https://www.adafruit.com/product/1312) and attempted some sample code. Does anyone know what I'm doing wrong or if NeoPixels are even supported? I can't get even one to blink. 

```
using System;
using System.Threading;
using Meadow;
using Meadow.Devices;
using Meadow.Foundation.Leds;


namespace MeadowApplication1
{
    public class MeadowApp : App<F7Micro, MeadowApp>
    {
        PwmLed neoPixel;

        public MeadowApp()
        {
            ConfigurePorts();
            BlinkLeds();
        }

        public void ConfigurePorts()
        {
            Console.WriteLine("Creating Outputs...");
            neoPixel = new PwmLed(Device.CreatePwmPort(Device.Pins.D02,800), TypicalForwardVoltage.Red);   
        }

        public void BlinkLeds()
        {
            Console.WriteLine("Starting main loop...");
            while (true)
            {
                int wait = 200;

                neoPixel.IsOn = true;
                Thread.Sleep(wait);
                neoPixel.IsOn = false;

            }
        }
    }
}
```
![IMG_20191114_090043](https://user-images.githubusercontent.com/7239809/68868836-cf04b800-06bd-11ea-9c54-96b940292b66.jpg)

**Comment by bryancostanich** [comment]
I believe we now support the timings necessary in our SPI config to make this work. To be investigated.

**Comment by bryancostanich** [comment]
Looks like we still need hold times. From Justin Wilson (@IngenuityMicro), this is the NetMF code that he used to support NeoPixel on Netduino:

```csharp
var spiConfig = new SPI.Configuration(Cpu.Pin.GPIO_NONE, false, 500, 500, false, false, 3200, SPI.SPI_module.SPI1);
            _spi = new SPI(spiConfig);
```

So csSetup and csHoldTime of 500 uSecs and ClockIdleState and ClockEdge of false

**Comment by gasia89** [comment]
I have a few spools of neopixels around here. I would be happy to lend a hand on this, if any help is needed? I would need a 1000ft overview on whats left to make it work, but I would be happy to help.

**Comment by jpearsonduluth** [comment]
Any update on this? Been checking out a couple times a month for about a year. Thanks!

**Comment by adrianstevens** [comment]
We don't have NeoPixel support yet but there is an APA102 driver that works well if you're interested in alternatives

**Comment by SteveStrong** [comment]
I am willing to help also ,  I will watch this issue to see if there are any changes to the status of neo-pixel support
