### ISSUE TITLE
AnalogJoystick DigitalPosition property is constantly `DownLeft`

### ISSUE THREAD

**Issue by jorgedevs** [WildernessLabs/Meadow.Foundation#283]
Ran the **Sensors.Hid.AnalogJoystick_Sample** in two different analog 2 axis joystick, and DigitalPosition is always returning `DownLeft` value.

Horizontal and Vertical output values are returning reliable data (-1.0 to 1.0 when moving the joystick to its full range), so looks like center is offset or **GetNormalizedPosition** might need further investigation.

**Comment by adrianstevens** [comment]
We were comparing relative positions to voltage - fixed + a little cleanup
