### ISSUE TITLE
Driver request: MCP23017 

### ISSUE THREAD

**Issue by upswing1** [WildernessLabs/Meadow.Foundation#303]
A driver for the MCP23016 would be a good option

**Comment by adrianstevens** [comment]
@upswing1 we're planning to ship support for the MCP23017 in the next release. Will that part do or are you looking specifically for Mcp23016 support?

**Comment by adrianstevens** [comment]
Updated title to MCP23017 re Slack discussion

And this driver is almost complete - I'll finish this weekend

**Comment by adrianstevens** [comment]
driver complete - will ship with next release
