### ISSUE TITLE
There are no unit tests in Meadow.Foundation

### ISSUE THREAD

**Issue by aholmes** [WildernessLabs/Meadow.Foundation#32]
There are no unit tests in Meadow.Foundation. Having these tests will help ensure consistency and quality in individual development and across the open source ecosystem.

**Comment by adrianstevens** [comment]
Thanks @aholmes, I love this idea. We're considering some other automation / validation options as we'll need to test against external peripherals.

I'll leave this open for now and we'll update as we make progress.

Cheers!

**Comment by aholmes** [comment]
@adrianstevens can you speak more to the other options? Testing against external peripherals sounds like integration testing. The intent with this commit is purely unit tests, which can mock such dependencies. The goal is to test and validate logic and code behavior, rather than physical or external behaviors. Integration and other automation often lives side-by-side with unit tests.

**Comment by adrianstevens** [comment]
Here's the test suite the team is building to support Meadow https://github.com/WildernessLabs/Meadow.TestSuite 

I'm going to close this issue but please feel free to continue the conversation there

Cheers!
