### ISSUE TITLE
Graphics `Image` draws corrupted bitmaps for some sizes

### ISSUE THREAD

**Issue by profexorgeek** [WildernessLabs/Meadow.Foundation#331]
I have solved this problem and will be issuing a PR to fix this issue but wanted to file the issue first with a clear description of the problem. Hopefully that's the proper etiquette for this repo!

**Problem**
I am experimenting with writing a light rendering library/game engine that runs on the Meadow. I followed some tutorials and quickly got image rendering working. However, when rendering bitmaps they were sometimes corrupted. At first I thought this was due to the program I was saving them from, so I tried MS Paint, Photoshop, and others. But the corruption appeared to be random. Sometimes images would draw fine, other times they would be garbled.

I eventually narrowed this down to the width of the image and discovered it was a padding issue. Consider the [original code](https://github.com/profexorgeek/Meadow.Foundation/blob/main/Source/Meadow.Foundation.Libraries_and_Frameworks/Graphics/MicroGraphics/Driver/Graphics.MicroGraphics/Image.cs#L128):

```csharp
var bytesPerRow = (int)(width * (BitsPerPixel / 8f));
// BMP row length is evenly divisible by 4
var rowPad = 4 - (bytesPerRow % 4);
```
If the row is 13 pixels wide, the bytes per row for a 24bit-depth image will be `13 * (24 / 8)` or 39 bytes per row.
The row padding will be `4 - (39 % 4)` or 1. Adding 1 to 39 gives you 40, which is a properly-padded bitmap line.

However, if the row is 12 pixels wide, the bytes per row for a 24bit image will be `12 * (24 / 8)` or 36 bytes per row.
The row padding will be `4 - (36 % 4)` or 4. Since the image was even, the mod is 0 and the padding is wrong (off by 4)! This results in a corrupt image being drawn.

To test and prove my fix I copied the `Image` source locally (I didn't want to try building the whole library from source) and created four images with two images having divisible widths and two not. I tested my fixes in my local `Image` copy with the following results.

Here is a demonstration of images that have a width divisible by 4 being corrupted but images with a non-divisible width drawing correctly:
![image](https://user-images.githubusercontent.com/711100/167322012-de922a70-8343-4bbb-9794-cccff9ee0d8d.png)

If you remove the subtraction, you have the inverse problem. An image that is divisible by 4 will draw correctly but non-divisible widths will be broken:
![image](https://user-images.githubusercontent.com/711100/167322039-68540f0e-ae96-4bc8-92ef-98ce8ced933a.png)

**Solution**
The solution is to check if the modulus operation is 0 and only perform the subtraction if it is not. Adding this check fixes the problem:
![image](https://user-images.githubusercontent.com/711100/167322093-70d2cb6d-a4f7-43bc-8d98-c741d51f272b.png)

I will issue a PR against this issue shortly!

**Comment by adrianstevens** [comment]
that is beautiful - thanks @profexorgeek! I'll get this merged 

@ctacke for visibility
