### ISSUE TITLE
References to the Graphics Library use old version

### ISSUE THREAD

**Issue by csuski** [WildernessLabs/Meadow.Foundation#38]
The TftSpi Project and others Display projects that I spot checked point to the GraphicsLibrary 0.8.7, instead of the latest 0.8.8

**Comment by adrianstevens** [comment]
The references will get updated as we update the drivers - and there are a lot of updated these days ;)

We're currently experiementing with our CI/CD system so you may see this happen as we test, but once our releases are fully automated the references will be kept in sync.

For this particular package, the was no code changes between 0.8.7 and 0.8.8.

And thank you @csuski for taking the time to file an issue, it's very appreciated. We'll likely make a few mistakes on the way to v1.0 ;)
