### ISSUE TITLE
Tcs3472x Driver

### ISSUE THREAD

**Issue by asharzaman** [WildernessLabs/Meadow.Foundation#438]
I am trying to use the Tcs34725 sensor with F7v1 and everything is wired up correctly. The application does detect the correct sensor. It doesn't matter what settings I try, the sensor is not detecting any changes. All of the RGB and Lux values are always zero. I have tried using it outside, inside, using a flashlight, or covering the sensor with my hand. 

I am using the example from: https://github.com/WildernessLabs/Meadow.Foundation/blob/e532eef01b71206038a0e8c4edfb6bf7afc7ef36/Source/Meadow.Foundation.Peripherals/Sensors.Light.Tcs3472x/Samples/Tcs3472x_Sample/MeadowApp.cs

I have tried it with both the last beta (0.6.x) and the current RC (0.9.x)
Thanks

**Comment by adrianstevens** [comment]
Unfortunately, this driver isn't complete and was accidentally published. I'll open a new driver request issue.

**Comment by adrianstevens** [comment]
opened issue #479

**Comment by adrianstevens** [comment]
closing issue as it's replaced by #479
