### ISSUE TITLE
Deprecate old nugets after RC1

### ISSUE THREAD

**Issue by adrianstevens** [WildernessLabs/Meadow.Foundation#450]
MCP23x08 

To investigate:
- [x]  https://www.nuget.org/packages/WildernessLabs.Meadow.Assemblies
- [x] https://www.nuget.org/packages/Meadow.Foundation.Sensors.Location.Gnss.NmeaParsing
- [x] https://www.nuget.org/packages/Meadow.Foundation.ICs.IOExpanders.Mcp23x08
- [x] https://www.nuget.org/packages/Meadow.Foundation.DataLoggers
- [x] https://www.nuget.org/packages/Meadow.Foundation.Sensors.Atmospheric.Htu21d
- [x] https://www.nuget.org/packages/Meadow.Foundation.ICs.ADC.Ads1x1x
- [x] https://www.nuget.org/packages/Meadow.Foundation.ICs.EEPROM.At24Cxx
- [x] https://www.nuget.org/packages/Meadow.Foundation.Grove.RTCs.RTC
- [x] https://www.nuget.org/packages/Meadow.Foundation.Grove.Servos.Servo
- [x] https://www.nuget.org/packages/Meadow.Foundation.Grove.Displays.LCD
- [x] https://www.nuget.org/packages/Meadow.Foundation.Grove.Sensors.Motion.PIRMotionSensor
- [x] https://www.nuget.org/packages/Meadow.Foundation.Grove.Sensors.Motion.MiniPIRMotionSensor
- [x] https://www.nuget.org/packages/Meadow.Foundation.Grove.Servos.Servo
- [x] https://www.nuget.org/packages/Meadow.Foundation.Grove.RTCs.RTC
- [x] https://www.nuget.org/packages/Meadow.Foundation.Grove.Sensors.Atmospheric.TemperatureHumiditySensor_HighAccuracyMini
- [x] https://www.nuget.org/packages/Meadow.Foundation.Grove.Displays.LCD
- [x] https://www.nuget.org/packages/Meadow.Foundation.Grove.Sensors.Motion.PIRMotionSensor
- [x] https://www.nuget.org/packages/Meadow.Foundation.Grove.Sensors.Motion.MiniPIRMotionSensor

**Comment by jorgedevs** [comment]
Grove drivers updated and published.
