### ISSUE TITLE
`Nxp74HC4051` and `Nxp74HC4067` are incorrectly named.

### ISSUE THREAD

**Issue by bryancostanich** [WildernessLabs/Meadow.Foundation#556]
**Describe the bug**

the `Nxp74HC4051` and `Nxp74HC4067` classes should just be called `74HC4051` and `74HC4067`, as those are the generics. Nexperia makes some of those chips, but then so do other folks.

**Comment by adrianstevens** [comment]
thx @bryancostanich  - I'll fix
