### ISSUE TITLE
SwitchingRainGauge example code references D15 causing error

### ISSUE THREAD

**Issue by fredmbarrett** [WildernessLabs/Meadow.Foundation#708]
The SwitchingRainGauge MeadowApp sample (Meadow.Foundation.Sensors.Weather) demonstrates initializing the Rain Gauge using the following code:
```
            // initialize the rain gauge driver
            rainGauge = new SwitchingRainGauge(Device.Pins.D15);
```
However, when running the app, an error occurs:
```
Unabled to create the Switching Rain Gauge: Unable to create input; channel is not capable of interrupts
```
F7FeatherV2 (and presumably V1) Pin 15 is not capable of interrupts (see http://beta-developer.wildernesslabs.co/Meadow/Meadow_Basics/IO/).

**Meadow.Foundation (please complete the following information as best as you can):**
 - NuGet package version: 1.1.0.0

**Developer tools (please complete the following information as best as you can):**
 - OS and version: Microsoft Windows [Version 10.0.22621.1992]
 - IDE and version: Visual Studio Professional 2022 17.6.2
 - Meadow extension for IDE version: 1.1.0

**Comment by adrianstevens** [comment]
Thanks Fred! I'll update the sample
