### ISSUE TITLE
Driver Request: HX711 Load Cell Amplifier

### ISSUE THREAD

**Issue by bryancostanich** [WildernessLabs/Meadow.Foundation#72]
Would be great to have a driver in `ICs` for the HX711 load cell sensor (analog input with amplifier). 

spark fun has a breakout board of it [here](https://learn.sparkfun.com/tutorials/load-cell-amplifier-hx711-breakout-hookup-guide).

Once we have a driver for the chip (or another chip driver like the NAU7802), then we can do a `LoadCell` Sensor that uses it.

**Comment by adrianstevens** [comment]
Driver published - closing issue
