### ISSUE TITLE
Driver Request: NAU7802 ADC with Amp chip/Load Cell Amp

### ISSUE THREAD

**Issue by bryancostanich** [WildernessLabs/Meadow.Foundation#73]
Would be nice to have a driver in `ICs` for the NAU7802. 

SparkFun has a breakout of it [here](https://www.sparkfun.com/products/15242). 

Once we have a driver for the chip (or another chip driver like the HX711), then we can do a `LoadCell` Sensor that uses it.

**Comment by adrianstevens** [comment]
Driver published - closing
