### ISSUE TITLE
Neopixel / ws2812 driver.

### ISSUE THREAD

**Issue by NevynUK** [WildernessLabs/Meadow.Foundation#747]
Recording investigation of the Neopixel timing for future reference.

The Neopixels (WS2812) LEDs use a time dependent signal to differentiate between a 0 and a 1.  There is no clock for synchronisation as there is with I2C or SPI.  The timings look something like this:

<img width="286" alt="WS2812Timing" src="https://user-images.githubusercontent.com/8407073/148438330-f1231dab-8eda-4022-a618-024f9e561c08.png">

The reset signal is a single low pulse greater than 50 microseconds (T<sub>reset</sub>).

For the remaining signals the timings are:

Signal | Time (nanoseconds)
------|----
TOH | 400
T0L | 800
T1H | 850
T1L | 450

All times have a tolerance of 150 nanoseconds giving the minimum and maximum timings of:

Signal | Min | Max
------|----|----
TOH | 250 | 550
T0L | 650 | 950
T1H | 700 | 1000
T1L | 300 | 600

Use of the SPI interface to use the COPI data line as a driver for the LEDs has been investigated and some issues were noted.  By changing the clock speed it should be possible to change the CPOI output to mimic the timing signal the Neopixels are expecting.

Given the tolerances a simple approach would be to adopt the following timings:

Signal | Time (nanoseconds)
------|----
TOH | 400
T0L | 800
T1H | 800
T1L | 400

So if we assume a single bit takes 200 nanoseconds to transmit then the number of bits becomes:

Signal | Number of bits
------|----
TOH | 2 (x 1)
T0L | 4 (x 0)
T1H | 4 (x 1)
T1L |  2 (x 0)

The next thing to consider is the time between the bytes.

The approach above was tried but did not work.  

Firstly, the data within the bytes was transmitted was OK, the problem was the time delay between the bytes.  This was consistently greater than the maximum time for T1H.

The second problem that was noted concerned the transmission of a repeated pattern.  A repeated pattern of 20 bytes of 0xA1 resulted in the first four bytes being transmitted as expected, i.e. the end of the 1 in 0xA1 dropped to low at the end of the clock for the byte.  It then raised to 1 at the start of the next byte.  The problem comes with bytes 5 and 6 (and the following bytes).  The data signal remains high at the end of byte 5 through to the start of byte 6.  Strictly speaking this is allowed but it messes up the theory of operation for this problem.

**Comment by adrianstevens** [comment]
thx @johnkattenhorn absolutely - closing issue
