### ISSUE TITLE
[MicroLayout] Clearing the Controls collection doesn't clear the screen

### ISSUE THREAD

**Issue by patridge** [WildernessLabs/Meadow.Foundation#764]
**Describe the bug**

If you add several controls and then show the screen, it will display them fine. But then if you clear out the controls, the screen will not continue to display whatever it showed previously. (I noticed this while working on #763, if some sample code is helpful.)

```csharp
screen.Controls.Clear();
```

I may be just missing a screen draw step, but I didn't expect one since adding controls seems to draw them immediately.

**Expected behavior**

After `Clear`ing the screen controls, the screen should be empty and display the default color.

**Meadow.Foundation (please complete the following information as best as you can):**
 - NuGet package version: v1.3.0

**Developer tools (please complete the following information as best as you can):**
 - Meadow extension for IDE version: v1.3.0

**Meadow (please complete the following information as best as you can):**
Most of these vaues can be found by running `meadow device info` using the [Meadow CLI](http://developer.wildernesslabs.co/Meadow/Meadow_Basics/Meadow_CLI/).
 - Meadow hardware version: Project Lab v3
 - Meadow OS version: v1.3.0.0

**Comment by ctacke** [comment]
Fixed as part of the LineChart PR
