### ISSUE TITLE
SPIClockConfiguration takes input in Khz, but output of SpeedKhz property is in hz

### ISSUE THREAD

**Issue by MarkAlanJones** [WildernessLabs/Meadow.Foundation#86]
I couldn't find the source, but it seems after creating the SPICLockConfiguration the SpeedKhz property reports HZ rather than KHZ

```
var config = new SpiClockConfiguration(6000, SpiClockConfiguration.Mode.Mode3);
Console.WriteLine($"SPI Speed {config.SpeedKHz}Khz");
```

result will be 
SPI Speed 6000000Khz 

rather than the 6000 input to the speedKhz parameter

```
public SpiClockConfiguration(long speedKHz, Mode mode);
public long SpeedKHz { get; set; }
```

**Comment by adrianstevens** [comment]
Thanks @MarkAlanJones! this was fixed in B3.11

closing issue
