### ISSUE TITLE
Unexpected class namespaces, possibly causing API docs build errors

### ISSUE THREAD

**Issue by patridge** [WildernessLabs/Meadow.Foundation#865]
Should all the files in this folder have the same namespace, potentially `Meadow.Foundation.Communication[s]`? Currently, there is a mix of three different namespaces in four files, one of which is causing a potential issue with generating API docs.

https://github.com/WildernessLabs/Meadow.Foundation/tree/develop/Source/Meadow.Foundation.Core/Communications

When we run the DocFX API Actions on WildernessLabs/Documentation, we get an error about duplicate UIDs (class-derived) between Meadow/Meadow.Hardware and Meadow.Foundation/Meadow.Hardware.

[Recent failing build](https://github.com/WildernessLabs/Documentation/actions/runs/7214894685/job/19657986209)

In digging into this repo, it looks like we have two classes using the `Meadow.Hardware` namespace. I don't know enough DocFX to know if that will fix those builds, but it does feel unexpected to have that namespace in here as well.

* https://github.com/WildernessLabs/Meadow.Foundation/blob/develop/Source/Meadow.Foundation.Core/Communications/I2cCommunications.cs#L3
* https://github.com/WildernessLabs/Meadow.Foundation/blob/develop/Source/Meadow.Foundation.Core/Communications/SpiCommunications.cs#L4

Additionally, in that folder, the **SerialTextFile** class has the `Meadow.Foundation.Communication` namespace. And then the sibling file **ByteCommsSensorBase** has the namespace `Meadow.Foundation`.

**Comment by adrianstevens** [comment]
reviewed - no changes needed 

closing issue
